# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_main_types.gd')

const Lobby = Types.Lobby
const TestTableDatatypes = Types.TestTableDatatypes
const TestEnum = Types.TestEnum
const TestType = Types.TestType
const TestNestedEnum = Types.TestNestedEnum
const TestScheduledTable = Types.TestScheduledTable
const TestEventTable = Types.TestEventTable
const Message = Types.Message
const Damage = Types.Damage
const User = Types.User
const UserData = Types.UserData


## example usage:
## [codeblock]
## # Reducer call returns a call object that the response will use to send out it's callback signals
## var call : SpacetimeDBReducerCall = SpacetimeDB.Main.reducers.example_reducer()
##
## # checking if the reducer call was send out successfully
## if call.error:
##     # handle reducer call error
##     pass
##
## # general callback signal
## call.response.connect(func(update:ReducerResultMessage) -> void: pass)
##
## # reducer successfully ran and returned with data (general subscription data)
## call.on_ok.connect(func(update:ReducerResultMessage) -> void: pass)
##
## # reducer successfully ran and returned without data
## call.on_ok_empty.connect(func(update:ReducerResultMessage) -> void: pass)
##
## # reducer failed to run and returned with the error string
## call.on_error.conect(func(err: String) -> void: pass)
##
## # reducer failed with internal error. not expected to be ever called.
## call.on_internal_error.conect(func(err: String) -> void: pass)
##
## waiting for the reducer response
## await call1.response
## [/codeblock]
var reducers: MainModuleReducers
var db: MainModuleDb

func _init() -> void:
	set_meta("module_name", "Main")
	name = "MainModule"
	reducers = preload('res://spacetime_bindings/schema/module_main_reducers.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_main_db.gd').new(p_local_db)
