# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainTestEventTableTable extends _ModuleTable

var id_2: MainTestEventTableId2UniqueIndex
var id: MainTestEventTableIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "test_event_table")
	id_2 = MainTestEventTableId2UniqueIndex.new(p_local_db)
	id = MainTestEventTableIdUniqueIndex.new(p_local_db)

func iter() -> Array[MainTestEventTable]:
	var rows: Array = super()
	var typed_array: Array[MainTestEventTable] = []
	typed_array.assign(rows)
	return typed_array
