# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainTestEventTable extends _ModuleTableType

const module_name : String = "Main"
const table_names: Array[String] = ['test_event_table']

@export var id: int
@export var id_2: int

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u32')
	set_meta('bsatn_type_id_2', &'u32')

## 0. id: int[br]
## 1. id_2: int[br]
static func create(p_id: int, p_id_2: int) -> MainTestEventTable:
	var result: MainTestEventTable = MainTestEventTable.new()
	result.id = p_id
	result.id_2 = p_id_2
	return result
